### ISSUE TITLE
use of undeclared type `Account` with scrypto v0.3

### ISSUE THREAD

**Issue by p3titcr0c0** [radixdlt/radixdlt-scrypto#169]
Hello,

I would need to send a bucket to an specific address from a function call.
Unfortunately on scrypto 0.3 there is no 'Account' type. However, I cannot find an equivalent to this operation with a bucket

```
Account::from(orders[i+1].1).deposit(payment.take(payment.amount()));
```

orders[i+1].1 is an Address & payment.take(payment.amount()) a Bucket.
I'm stuck on sending a BUcket so I only have the example in 0.2 to show. Thank you for your help

**Comment by devmannic** [comment]
The equivalent call to a component with the "deposit" function looks like this:
```rust
        let args = vec![scrypto_encode(&bucket)];
        let rtn = call_method(address, "deposit", args);
        // scrypto_unwrap(scrypto_decode(&rtn)) // if you want to decode the return value
```

`Account` was removed because it's really just an interface.  If you want to see an example of adding it back as a trait, take a look at my `scrypto_statictypes` library.  Specifically here: https://github.com/devmannic/scrypto_statictypes/blob/3e46be3ea9646069cec515aff32fc2c63397d02e/src/exts.rs#L16
