### ISSUE TITLE
Geting component/vault from Substore

### ISSUE THREAD

**Issue by a137x** [radixdlt/radixdlt-scrypto#358]
Good evening.
In version 0.4.1 I can't find a good replacement for thngs that existed in version 0.3.0

in ```radix_engine::ledger::memory::InMemorySubstateStore```
there were two functions:
```rust
   fn get_component(&self, address: Address) -> Option<Component> {
        self.components.get(&address).map(Clone::clone)
    }

    fn get_vault(&self, component_address: &Address, vid: &Vid) -> Option<Vault> {
        self.vaults
            .get(&(component_address.clone(), vid.clone()))
            .map(Clone::clone)
    }
```
Which existed prior version 0.4.0, is gone now.

This function were useful, in conjunction with other stuff, for getting of vaults for particular component.

The thing looked like this:
```rust
    let mut ledger = InMemorySubstateStore::with_bootstrap();
    
    pub fn get_account_vaults(
        &mut self,
        component_address: ComponentAddress,
    ) -> HashMap<ResourceAddress, Contents> {
        let ledger = self.executor.substate_store();
        let component = ledger.get_component(component_address).unwrap();

        let state = component.state();
        let validated_data = validate_data(state).unwrap();
        validated_data
            .lazy_maps
            .iter()
            .flat_map(|mid| TestEnv::get_lazymap_info(ledger, &component_address, &mid))
            .collect()
    }

    fn get_lazymap_info(
        ledger: &L,
        component_address: &ComponentAddress,
        id: &Mid,
    ) -> Vec<(ComponentAddress, Contents)> {
        let lazy_map = ledger.get_lazy_map(component_address, id).unwrap();
        lazy_map
            .map()
            .iter()
            .flat_map(|(_, data)| {
                let validated_data = validate_data(data).unwrap();
                validated_data
                    .vaults
                    .iter()
                    .map(|vid| TestEnv::get_vault_info(ledger, component_address, vid))
                    .collect::<Vec<(ResourceAddress, Contents)>>()
            })
            .collect()
    }

    pub enum Contents {
        Amount(Decimal),
        NonFungibleIds(Vec<NonFungibleId>),
    }

```
How to achieve the desirable in 0.4.1 ?

**Comment by 0xOmarA** [comment]
Hey @a137x, I've looked into this a little bit and it indeed seems to not be possible due to the `InMemorySubstateStore` having no methods to obtain the keys in the substate store. We have discussed this internally and this is something we're looking to add with v0.5.0.

For the time being, if you wish to proceed with an implementation for v0.4.0, you can do one of the following:
1- Implement a simple `SubstateStore` in your library and ask people to make use of it. This substate store can be a modified version of the `InMemorySubstateStore` with an additional method for the retrieval of the keys. 

2- Parse out the string obtained from converting the substate store to a string and get the lazymap keys based on that. 

I understand that the approaches that I described might not be optimal. So, if you would like, you can wait until v0.5.0 when we implement this method on the `InMemorySubstateStore`.

**Comment by 0xOmarA** [comment]
Being able to query the balance of an account is now possible with #426.
