### ISSUE TITLE
Clear the difference between "create_proof" and "withdraw" method on the account component

### ISSUE THREAD

**Issue by unghuuduc** [radixdlt/radixdlt-scrypto#365]
The [Account component](https://github.com/radixdlt/radixdlt-scrypto/blob/main/assets/account/src/lib.rs) didn't clearly draw a line between "create_proof" and "withdraw" method but treat those as the same. This will cause problem when create a proof of a withdraw-restricted resource.

For an example: I would create a KYC badge by this resource AccessRule `.restrict_withdraw(rule!(deny_all), LOCKED)`
But later, because of the problem, users cannot create proofs that they have the KYC badge through "create_proof" method.

How about include a second AccessRule that the AccessRule `.restrict_withdraw(...)` would create, instead of just intergrate the rule on the `withdraw_rule`, this would clearly draw a line between "create_proof" and "withdraw" method.

**Comment by 0xOmarA** [comment]
Hi Peter, a `restricted_withdraw` resource can still have proofs created from it even when it's stored in the account component. 

If you would like to test this out to verify that it indeed works as expected, here is the transaction manifest file required to create a restricted withdraw token:

```sh
CALL_FUNCTION PackageAddress("010000000000000000000000000000000000000000000000000001") "System" "new_resource" Enum("Fungible", 18u8) HashMap<String, String>() HashMap<Enum, Tuple>(Enum("Withdraw"), Tuple(Enum("DenyAll"), Enum("LOCKED"))) Some(Enum("Fungible", Decimal("1000")));
CALL_METHOD_WITH_ALL_RESOURCES ComponentAddress("${account_component}") "deposit_batch";
```

And here is a sample transaction manifest that attempts to create a proof of this newly created resource:

```sh
CALL_METHOD ComponentAddress("${account_component}") "create_proof" ResourceAddress("${resource_address}");
```

If you give this a try, you will see that the second transaction succeeds with no problem at all. But why?  This is because the `AccessRules` on the account component only define _who_ can call these methods and nothing else.

**Comment by unghuuduc** [comment]
Thanks, I got it now, will close the issue.
