### ISSUE TITLE
Return keyword caused BucketRef not dropping

### ISSUE THREAD

**Issue by iamyulong** [radixdlt/radixdlt-scrypto#76]
**From @MrAir on Discord:**

---

Hey all, so I'm now in the process of going through the two hour scrypto video and I have a weird error that does not make sense to me.

I'm now at the point in the video where the team is talking about badges and how they can be made. For the withdraw method, I have written the following:
```
#[auth(admin_badge)]
pub fn withdraw(&mut self) -> Bucket {
  return self.xrd_vault.take_all();
}
```

For some reason, calling this method fails with the following error:
```
Transaction Status: FAILURE
Execution Time: 11 ms
Instructions:
├─ DeclareTempBucketRef
├─ CallMethod { component: 02526629b90e1142492e934fbe807b446935407064db3ea2fcf856, method: "withdraw", args: [1, 03c71ddd6b7967d6fd7d0e4a437c45f4ceac132d74d948a07af561] }
├─ BorrowFromContext { amount: 1, resource_def: 03c71ddd6b7967d6fd7d0e4a437c45f4ceac132d74d948a07af561, to: Rid(0) }
├─ CallMethod { component: 029849b6426bf644066da5b7dd8b0c119cf75ce225523046cb23d5, method: "withdraw", args: [Rid(0)] }
├─ DropAllBucketRefs
├─ DepositAllBuckets { account: 02526629b90e1142492e934fbe807b446935407064db3ea2fcf856 }
└─ End { signers: [04005feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9] }
Results:
├─ Ok(None)
├─ Ok(Some(Bid(1)))
├─ Ok(None)
└─ Err(ResourceCheckFailure)
Logs: 0
New Entities: 0
Error: TransactionFailed
```

However, if I change this method to be the following:
```
#[auth(admin_badge)]
pub fn withdraw(&mut self) -> Bucket {
  self.xrd_vault.take_all()
}
```
then I now longer get an error when calling the withdraw method with the badge. 

Why is it that removing the explicit return statement fix this issue? Isn't `self.xrd_vault.take_all()` and return `self.xrd_vault.take_all();` equivalent?

**Comment by devmannic** [comment]
This looks like a bug in the auth macro.  The return inside of the `#f_body` makes the `#drop` not reached.

See:

 https://github.com/radixdlt/radixdlt-scrypto/blob/f3a6d46ef1c0f381a3c64cc7026a83fa38e975e9/scrypto-derive/src/auth.rs#L71

This would be my fix.  Tested (briefly) and seems to work.

```diff
-            let output = #f_body;
+            let func = || #f_body;
+            let output = func();
```
And I think this implementation, which lets all of the parameters be captured by the closure instead of recreating them as parameters for the closure is a better approach.  But I'm not positive.  Let me know which approach you think is right and I can submit a PR for it so it gets more thoroughly tested.

**Comment by iamyulong** [comment]
Yes, closure is the right approach. To make function work, we will need to forward arguments and `auth`.

Feel free to make a PR but and ensure both cases are tested: reading auth & not.

**Comment by devmannic** [comment]
I believe my example above which does not explicitly name the arguments, but none the less captures them in the closure is correct.  Did you want to do something else based on your comment:
> To make function work, we will need to forward arguments and auth
I don't think they need to be explicitly named since the closure will capture any used variables (and it's probably more optimized this way too).

I've tried the alternative, explicitly naming the arguments, and it leads to lots of extra code to filter out or modify the self argument since you can't name a formal parameter "self" in a closure.  I don't have it totally working yet, but it seems unnecessarily.

I'll push the PR as is and you can see if the simpler way has any drawbacks I haven't uncovered.

**Comment by devmannic** [comment]
One more question.  It occurs to me adding a test case for this along with the fix is a good idea.  But I'm not sure the best place to do that.  Modifying the examples is easiest (that's how I tested it), but also makes for less idiomatic Rust which isn't so good for an example.  Thoughts?
