### ISSUE TITLE
Prevent dangling vaults?

### ISSUE THREAD

**Issue by iamyulong** [radixdlt/radixdlt-scrypto#87]
Currently, we are allowed to create vaults freely, with or without attaching it to a component. This may cause resource locked in a vault that nobody effectively owns, by careless developers. Should we do something about this?

**Comment by backyard-coder** [comment]
The only purpose for this that I could think of right now, is token burns. Just for the fun of it, I have created a TokenBurn component in the community repo: https://github.com/radixdlt/community-scrypto/pull/22

If there is a better way to implement token burning, however, I would be all for making dangling vaults impossible. I would think that in 99% of cases a dangling vault would be a bug rather than a feature, and would cause the developer a lot of grief.

**Comment by cbisaillon** [comment]
I also see this as a bug rather than a feature. I think that if we have the security check for dangling buckets, we should also have it for vaults. @backyard-coder I think your TokenBurn example could be implemented by having a HashMap mapping ResourceDef => Vault (Like the account component). The component would have a way to burn the tokens (add them to the HashMap) but no way to take from those vaults

**Comment by devmannic** [comment]
> If there is a better way to implement token burning,
There's already an API for burning tokens and (with the new APIs coming) even has fine grained permissions.

This type of "faux burning" breaks the permission model since you wouldn't need a badge with burn permission to effectively burn the token.

This "faux burning" is not a good use case for dangling Buckets/Vaults at all IMHO.  Even when used in this way dangling containers would still be a bug.  In addition to the badge permission bypass we have the functions which query the resource supply.  These would now be incorrect since they aren't the actual available supply and there's no (reasonable) way to calculate it once the Vault is lost.

**Comment by backyard-coder** [comment]
> @backyard-coder I think your TokenBurn example could be implemented by having a HashMap mapping ResourceDef => Vault (Like the account component). The component would have a way to burn the tokens (add them to the HashMap) but no way to take from those vaults

Sure, but what if I simply added a withdraw method later on, which would allow me to withdraw all supposedly burnt tokens? In resim it is possible to change a deployed components code. I am not sure if that will also be possible on the actual ledger.

Otherwise, I totally agree with @devmannic: having a token burning concept in resource/permission model makes much more sense!

**Comment by talekhinezh** [comment]
@iamyulong Can we close this?
