### ISSUE TITLE
Idea: add a way to truncate Decimal

### ISSUE THREAD

**Issue by cbisaillon** [radixdlt/radixdlt-scrypto#93]
I am trying to remove the floating part of a Decimal but can't find an easy way to do it (other than transforming to String and removing the floating part from there).

**Comment by devmannic** [comment]
The current `Decimal` implementation is a nice minimal design for crossing the wasm boundary but ti's not particularly good for actually doing math let alone finance math apart from simple adding and subtracting (and I think that's ok, and probably a wise choice).

Do answer your question about truncating: `Decimal` is a simple wrapper around an `i128` with an implied (but non pub!) `PRECISION` of 1e-10.  (I think the PRECISION should be pub or have better conversation functionality than going to/from bytes)

So you can do is something like the following (though there might be better ways)

```rust
fn test_3() {
    let d: Decimal = Decimal::from_str("123.456").unwrap();
    let i: i128 = d.0;  // Decimal is just a tuple of i128
    let part = i % 1_000_000_000_000_000_000i128;
    let truncated: Decimal = Decimal(i - part);
    let onetwentythree: Decimal = Decimal::from_str("123").unwrap();
    assert_eq!(truncated, onetwentythree);
}
```

My recommendation for doing anything more complicated is to convert to an integer representation that is more powerful and you can handle precision as you need.  For example here is what I use in my current work:

Use the `num-bigint` and `num-traits` crates for arbitrary precision integers and convert to/from Decimal as needed.

The "default-features = false" is required to ensure no floating point operations are used, and even then certain functionality (like parsing) needs to be avoided because they *still* use floats.

```toml
# Cargo.toml
[dependencies]
num-bigint = { version = "0.4.3", default-features = false, features = [] }
num-traits = "0.2.14
```

```rust
use num_bigint::BigInt;
use num_traits::{ToPrimitive};

fn decimal_from_bigint(b: BigInt, precision_bits: u16) -> Option<Decimal> {
    let b = b >> precision_bits;
    let i: i128 = b.to_i128()?;
    Some(Decimal(i))
}

fn bigint_from_decimal(d: Decimal, precision_bits: u16) -> BigInt {
    let b: BigInt = d.0.into();
    b << precision_bits
}
```
Note these examples ignore PRECISION which is fine as long as you understand the implications for the math being done.

**Comment by iamyulong** [comment]
Rounding is a very useful decimal operation, will add it to our backlog.

The intention of `Decimal` is to provide decimal math with a universal, fixed precision (`10^-18`)  to meet 99% of the use cases; unless the required function is not provided, like in this case, we should avoid operating on its underlying implementation, as it may break component interoperability.

**Comment by devmannic** [comment]
> The intention of Decimal is to provide decimal math with a universal, fixed precision (10^-18) to meet 99% of the use cases; 

That sounds good, but I found it not usable when working on my a bonding curve implementation.  Because any math that does even a little multiplication or division (let alone exponentiation and roots) has to contend with loss of precision and overflow so having a way to use higher (arbitrary) precision integers is really mandatory for Scrypto IMHO.  As it is, the EVM uses 256 bit ints and because of WASM limitations we only have 128 bit.

> we should avoid operating on its underlying implementation

I agree, but the current definition of `Decimal` is: `pub struct Decimal(pub i128);` So if the intention is to hide the i128 implementation detail then it should not be pub, but instead something like `struct Decimal { data: i128 }`

The current API for conversion is `to_vec` and `TryFrom<&[u8]>`  Since the format of the u8 wasn't documented anywhere (though clearly it's little endian) I thought it better to use the i128 field.  If the intention is for those to be the canonical conversion routines they should have some documentation.  The `PRECISION` being private is still problematic since that's effectively an implementation details that need to be understood when using the conversion APIs too, but documentation fixes that too.  Finally, it's really not very performant to use a vector for conversion as long as the size continues to fit in an integer type (such as i128).  Maybe consider an explicit API for conversion To/From an (maybe Option) i128 while hiding the implementation.

**Comment by kroggen** [comment]
@devmannic

For lossless math you can use fractions.

One option is `num-rational`. I sent a suggestion before [here](#55)

But it is also possible to do some computations without the library

Eg: instead of storing a "ratio" in a variable, just do the computation with the 2 values that create the ratio

Instead of this:

```python
a = 5
b = 7
ratio = a / b
result = value * ratio
```

Do this:

```python
a = 5
b = 7
result = value * a / b
```

**Comment by devmannic** [comment]
> For lossless math you can use fractions.

Thanks for the tip @kroggen -- I've been using the other `num` libraries but didn't look closely at `num-rational` because I still needed `nth_root` functionality.  I was also already using simple tricks like that such as distributing and only dividing at the end.

But, your comment spurred me into looking deeper at `num-rational` so thank you.  And it already has a  `BigRational` based on `BigInt` and so I just built the rest I needed on top of it, as an alternate implementation to what I was already doing with `BigInt` alone.

Now both implementations can be chosen by feature flag on my bonding curve AMM.  If you're interested you can read more in the PR here https://github.com/radixdlt/community-scrypto/pull/24 and specifically in `defi/amms/bonding/src/number.rs`

**Comment by 0xOmarA** [comment]
Regarding rounding and truncation, this was added to Scrypto with [v0.4.0](https://github.com/radixdlt/radixdlt-scrypto/blob/v0.4.0/scrypto/src/math/decimal.rs).
